version: '3.5'

networks:
  mdb-network:
    name: mdb-network


services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mdb-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - mdb-network
    depends_on:
      - mongo

#  mdb-data:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    platform: linux/x86_64
#    ports:
#      - "8455:8455"
#    networks:
#      - mdb-network


  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: stock-market-rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./.docker-data/.rabbit-data:/var/lib/rabbitmq/
      - ./.docker-data/.rabbit-log:/var/log/rabbitmq
      - ./.rabbit-plugins:/etc/rabbitmq/enabled_plugins
