apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yf-data-collect-hpa
  namespace: mdb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
