apiVersion: apps/v1
kind: Deployment
metadata:
  name: yf-data-collect
  namespace: mdb
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: yf-data-collect
  template:
    metadata:
      labels:
        app: yf-data-collect
    spec:
      containers:
        - name: api
          image: ghcr.io/ivosieme/yf-data-collect:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8455
          env:
            - name: APP_ENV
              value: 'prod'
            - name: YAHOO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: yahoo-api-key
                  key: yahoo-api-key
      imagePullSecrets:
        - name: ghcr-creds
